### ISSUE TITLE
ModuleNotFoundError: No module named 'tomllib' 

### ISSUE THREAD

**Issue by anitagraser** [Teakinboyewa/SpatialAnalysisAgent#18]
I have installed all dependencies listed in the README, but I get `ModuleNotFoundError: No module named 'tomllib' `.

If Google results are reliable, this indicates that the plugin requires Python >= 3.11. This info should be added to the Readme.

**Comment by Teakinboyewa** [comment]
Thank you @anitagraser .
Were you able to install the 'tomllib' using Python version >= 3.11?
