### ISSUE TITLE
Trying to integrate open-source models instead of openai models, need help

### ISSUE THREAD

**Issue by mr-sarthakgupta** [Teakinboyewa/SpatialAnalysisAgent#23]
Hi, I'm working on a fork of this project (https://github.com/mr-sarthakgupta/SpatialAnalysisAgent/) to integrate open-source models from huggingface instead of openai models into this project but am facing issues with the refactoring.

Specifically I'm not able to get past refactoring the function `add_data_overview_to_data_location` in `SpatialAnalysisAgent_DataEye/dataeye.py` where the response is passed to json.loads. I would like to know what would be the expected structure of the json expected in the LLM output. Any suggestions regarding any specific framework for enforcing json output from the LLM are welcome!

@Teakinboyewa @tea5209 @yumemio @anitagraser

**Comment by mr-sarthakgupta** [comment]
Thanks a lot @yumemio! I'm using huggingface pipelines as of now and was thinking of moving to ollama or llama.cpp for better speed in the future. I will use ollama only now that structured output is necessary, I was also considering [langchain's output parser](https://python.langchain.com/docs/concepts/output_parsers/) but am unsure about its efficacy.

 I had another question: right now I'm running the agent using the QGIS UI, identifying the bug, editing the code, loading it up in QGIS. Essentially this way of iteration feels very slow to me and I don't know any other method since this is my first GIS related project. Is there a better way to do this?

**Comment by mr-sarthakgupta** [comment]
Hi @yumemio this is a gentle reminder regarding the above, kindly let me know about the development process for QGIS plugins and whether there's a better method out there

**Comment by yumemio** [comment]
@mr-sarthakgupta Sorry for not being very responsive. As for the development method, the process I followed was very similar to what you described: edit the code using an external editor and see what comes up on the plugin's log view.

I'm still kind of new to QGIS plugin development, so I am not sure if this is the most efficient approach. Sorry that I can't be of more help!
